server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:master_redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  client-type: lettuce

  kafka:
    bootstrap-servers: kafka-1:9092
    url-shortener-event-topic: url-shortener-event-topic
    topic-replication-factor: 3
    topic-partitions: 3
    producer:
      acks: all
      delivery-timeout: 12000
      linger: 0
      request-timeout: 3000
      idempotence: true
      inflight-requests: 5
      properties:
        retries: 3
        compression.type: snappy
        batch.size: 16384

logging:
  level:
    root: info

app:
  short_url_prefix: "my_short_url/"
  local_hash:
    capacity: 20
    min_value: 10
  hash:
    batch_size: 200
    expiration_period_hours: 1

  async:
    hash_generator:
      core_pool_size: 5
      max_pool_size: 10
      queue_capacity: 500
      thread_name_prefix: "AsyncExecutor-"
  local_hash_refill:
    core_pool_size: 5
    max_pool_size: 10
    queue_capacity: 500
    thread_name_prefix: "RefillExecutor-"
  scheduling:
    hash:
      cron: 0 0 0 * * *
    removal:
      cron: 0 0 0 * * *
      months_before_expiration: 12