server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      client-type: lettuce

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    url-shortener-event-topic: ${SPRING_KAFKA_URL_SHORTENER_EVENT_TOPIC}
    topic-replication-factor: ${SPRING_KAFKA_TOPIC_REPLICATION_FACTOR}
    topic-partitions: ${SPRING_KAFKA_TOPIC_PARTITIONS}
    producer:
      acks: ${SPRING_KAFKA_PRODUCER_ACKS}
      delivery-timeout: ${SPRING_KAFKA_PRODUCER_DELIVERY_TIMEOUT}
      linger: ${SPRING_KAFKA_PRODUCER_LINGER}
      request-timeout: ${SPRING_KAFKA_PRODUCER_REQUEST_TIMEOUT}
      idempotence: ${SPRING_KAFKA_PRODUCER_IDEMPOTENCE}
      inflight-requests: ${SPRING_KAFKA_PRODUCER_INFLIGHT_REQUESTS}
      properties:
        retries: ${SPRING_KAFKA_PRODUCER_PROPERTIES_RETRIES}
        compression.type: ${SPRING_KAFKA_PRODUCER_PROPERTIES_COMPRESSION_TYPE}
        batch.size: ${SPRING_KAFKA_PRODUCER_PROPERTIES_BATCH_SIZE}

aws:
  region: eu-central-1

  sns:
    topic: url-events-topic


logging:
  level:
    root: info

app:
  short_url_prefix: "my_short_url/"
  local_hash:
    capacity: 20
    min_value: 10
  hash:
    batch_size: 200

  local_hash_refill:
    core_pool_size: 1
    max_pool_size: 3
    queue_capacity: 500
    thread_name_prefix: "RefillExecutor-"
  scheduling:
    hash:
      cron: 0 0 0 * * *
    removal:
      cron: 0 0 0 * * *
      months_before_expiration: 12