test:
  user-id: 1
  x-user-id-header: x-user-id

spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    url-shortener-event-topic: url-shortener-event-topic
    topic-replication-factor: 1
    topic-partitions: 3
    producer:
      acks: all
      delivery-timeout: 12000
      linger: 0
      request-timeout: 3000
      idempotence: true
      inflight-requests: 5
      properties:
        retries: 3
        compression.type: snappy
        batch.size: 16384

  datasource:
    url: jdbc:postgresql://master_postgres:5432/postgres
    username: user
    password: password
  data:
    redis:
      host: master_redis
      port: 6379