apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  SPRING_DATA_REDIS_HOST: "redis-cluster-ip-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-cluster-ip-service:5432/postgres"
  POSTGRES_DB: "postgres"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_URL_SHORTENER_EVENT_TOPIC: "url-shortener-event-topic"
  SPRING_KAFKA_TOPIC_REPLICATION_FACTOR: "1"
  SPRING_KAFKA_TOPIC_PARTITIONS: "3"
  SPRING_KAFKA_PRODUCER_ACKS: "all"
  SPRING_KAFKA_PRODUCER_DELIVERY_TIMEOUT: "12000"
  SPRING_KAFKA_PRODUCER_LINGER: "0"
  SPRING_KAFKA_PRODUCER_REQUEST_TIMEOUT: "3000"
  SPRING_KAFKA_PRODUCER_IDEMPOTENCE: "true"
  SPRING_KAFKA_PRODUCER_INFLIGHT_REQUESTS: "5"
  SPRING_KAFKA_PRODUCER_PROPERTIES_RETRIES: "3"
  SPRING_KAFKA_PRODUCER_PROPERTIES_COMPRESSION_TYPE: "snappy"
  SPRING_KAFKA_PRODUCER_PROPERTIES_BATCH_SIZE: "16384"